---
title: "Materials"
description: |
  Materials for Gov 2003: Causal Inference with Applications
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

## Lecture Notes

0. Introduction: [PDF](files/00_intro.pdf) |  [Handout PDF](files/00_intro_handout.pdf)
1. Potential Outcomes: [PDF](files/01_potential_outcomes.pdf) |  [Handout PDF](files/01_potential_outcomes_handout.pdf)
1. Randomized Experiments and Randomization Inference: [PDF](files/02_experiments.pdf) |  [Handout PDF](files/02_experiments_handout.pdf)
1. Inference for the ATE: [PDF I (ATE)](files/03_ate_inference.pdf) | [Handout I (ATE)](files/03_ate_inference_handout.pdf) | [PDF II (Blocking)](files/03_blocking_pairs.pdf) | [Handout II (Blocking)](files/03_blocking_pairs_handout.pdf)
1. Regression and Experiments: [PDF](files/04_regression.pdf) | [Handout](files/04_regression_handout.pdf)
1. Observational Studies: [PDF](files/05_observational_studies.pdf) | [Handout](files/05_observational_studies_handout.pdf) | [PDF II (Sensitivity Analysis and Bounds)](files/05_sens_partial.pdf) | [Handout II (Sensitivity Analysis and Bounds)](files/05_sens_partial_handout.pdf)
1. Instrumental Variables: [PDF I (Noncompliance)](files/06_iv.pdf) | [Handout I (Noncompliance)](files/06_iv_handout.pdf) | [PDF II (TSLS)](files/06_tsls.pdf) | [Handout II (TSLS)](files/06_tsls_handout.pdf)
1. Matching and Weighting: [PDF I (Matching)](files/07_matching.pdf) | [Handout I (Matching)](files/07_matching_handout.pdf) | [PDF II (Weighting)](files/07_weighting.pdf) | [Handout II (Weighting)](files/07_weighting_handout.pdf)

## Section Notes

1. Potential Outcomes: [PDF](files/section1_gov2003_2021F.pdf) | [Annotated PDF](files/section1_gov2003_2021F_annotated.pdf)
1. Randomized Experiments and Randomization Inference: [PDF](files/section2_gov2003_2021F.pdf) | [Annotated PDF](files/section2_gov2003_2021F_annotated.pdf)
1. Inference for the ATE: [PDF](files/section3_gov2003_2021F.pdf) | [Annotated PDF](files/section3_gov2003_2021F_annotated.pdf)
1. Regression and Experiments: [PDF](files/section4_gov2003_2021F.pdf) | [Annotated PDF](files/section4_gov2003_2021F_annotated.pdf)
1. Observational Studies: [PDF](files/section5_gov2003_2021F.pdf) | [Annotated PDF](files/section5_gov2003_2021F_annotated.pdf) | [PDF II](files/section6_gov2003_2021F.pdf) | [Annotated PDF II](files/section6_gov2003_2021F_annotated.pdf)
1. Instrumental Variables: [PDF](files/section7_gov2003_2021F.pdf) | [Annotated PDF](files/section7_gov2003_2021F_annotated.pdf)
1. Matching and Weighting: [PDF](files/section8_gov2003_2021F.pdf) 

## Problem Sets

1. Potential Outcomes: [Solution](files/pset1_gov2003_2021F_solution.pdf)
1. Randomized Experiments and Randomization Inference: [Solution](files/pset2_gov2003_2021F_solution.pdf) 
1. Inference for the ATE: [Solution](files/pset3_gov2003_2021F_solution.pdf) 
1. Regression and Experiments: [Solution](files/pset4_gov2003_2021F_solution.pdf) 
1. Observational Studies: [Solution](files/pset5_gov2003_2021F_solution.pdf) 
